# Crumbs configuration file
# Place in project root as .crumbs.yaml or in ~/.crumbs/config.yaml

# Backend type: sqlite, dolt, dynamodb
backend: sqlite

# Data directory for local backends (sqlite, dolt)
# Relative paths are relative to the current working directory
datadir: .crumbs

# Dolt backend configuration (required when backend: dolt)
# dolt:
#   dsn: "file:/path/to/dolt/repo"
#   branch: main

# DynamoDB backend configuration (required when backend: dynamodb)
# dynamodb:
#   tablename: crumbs
#   region: us-east-1
#   endpoint: http://localhost:8000  # Optional, for local testing
