id: rel02.1-uc003-self-hosting
title: Self-Hosting
summary: 'The cupboard CLI tracks development work on the crumbs repository. The

  do-work.sh and make-work.sh scripts run end-to-end using cupboard commands.

  This validates that cupboard works as an issue tracker for real agent

  workflows.

  '
actor: Coding agent (e.g., Claude Code) working on the crumbs codebase via do-work.sh
  and make-work.sh scripts
trigger: Cupboard CLI providing the issue-tracking commands that scripts need
flow:
- id: F1
  step: 'Implement issue-tracking CLI commands: ready, create, update, close, show,
    list, comments'
- id: F2
  step: 'Support JSON output: the --json flag outputs JSON for script consumption;
    without it, output is human-readable'
- id: F3
  step: 'Handle crumb creation options: cupboard create accepts --type, --title, --description,
    --parent, --labels'
- id: F4
  step: 'Follow state transitions: draft, pending, ready, taken, pebble, dust (prd003-crumbs-interface
    R2)'
- id: F5
  step: 'Integrate do-work.sh script: use cupboard commands to pick a task, claim
    it, and close it after completion'
- id: F6
  step: 'Integrate make-work.sh script: use cupboard commands to list existing issues
    and create new ones'
- id: F7
  step: 'Handle JSONL sync: no explicit sync command needed; SQLite backend syncs
    on every write using immediate sync strategy (prd002-sqlite-backend R5, R16)'
- id: F8
  step: 'Reference cupboard commands in agent workflow rule: .claude/rules/ references
    cupboard commands for interactive use'
- id: F9
  step: 'Commit JSONL files to git: per eng01-git-integration, JSONL files are committed
    as part of session completion'
touchpoints:
- T1: 'cupboard CLI (cmd/cupboard): issue-tracking commands ready, create, close,
    update, show, list, comments (prd003-crumbs-interface R3, R4, R10)'
- T2: 'Cupboard library (pkg/types): Cupboard interface with GetTable, Table interface
    for CRUD, Crumb/Property entities (prd001-cupboard-core R2, R3; prd003-crumbs-interface
    R1)'
- T3: 'SQLite backend (internal/sqlite): storage, JSONL persistence, query engine,
    entity hydration (prd002-sqlite-backend R1-R5, R12-R15)'
- T4: 'do-work.sh: task picking (Fetch), worktree management, agent invocation (prd003-crumbs-interface
    R9, R10)'
- T5: 'make-work.sh: work creation (Set), issue import (prd003-crumbs-interface R3;
    prd001-cupboard-core R3.3)'
- T6: '.claude/rules/: agent workflow instructions (eng01-git-integration)'
success_criteria:
- id: S1
  criterion: cupboard ready returns available tasks as JSON
- id: S2
  criterion: cupboard create --type task --title 'Test' --description '...' creates
    a crumb
- id: S3
  criterion: cupboard update <id> --status in_progress transitions crumb state
- id: S4
  criterion: cupboard close <id> marks crumb as closed
- id: S5
  criterion: cupboard list --json returns all crumbs as JSON
- id: S6
  criterion: do-work.sh runs a full cycle (pick, worktree, Claude, merge, close) using
    cupboard
- id: S7
  criterion: make-work.sh creates issues via cupboard and commits JSONL changes
out_of_scope:
- Multi-agent coordination (single agent self-hosting)
- Remote backends (SQLite only)
- Trail-based worktree integration in the CLI (trails are worktrees per eng01-git-integration,
  but the CLI does not manage git worktrees; do-work.sh handles that)
test_suite: test-rel02.1
