id: rel01.0-uc005-crumbs-table-benchmarks
title: Crumbs Table Performance Benchmarks
summary: 'A developer measures the performance of core Table interface operations
  on the

  crumbs table to establish baseline metrics. The benchmarks cover Get, Set

  (create and update), Delete, and Fetch operations at various data scales,

  providing ns/op, B/op, and allocs/op for each operation. These baselines guide

  optimization decisions and detect performance regressions.

  '
actor: Developer measuring Table performance
trigger: Need to establish baseline performance for core crumbs Table operations
flow:
- id: F1
  step: 'Build benchmark tests: create Go benchmark functions in internal/sqlite that
    exercise crumbs Table operations'
- id: F2
  step: 'Seed test data: for each scale (10, 100, 1000, 10000 crumbs), populate the
    crumbs table with sample entities'
- id: F3
  step: 'Benchmark Get at 10 crumbs: measure Table.Get latency with random ID selection
    from 10 seeded crumbs'
- id: F4
  step: 'Benchmark Get at 100 crumbs: measure Table.Get latency from 100 seeded crumbs'
- id: F5
  step: 'Benchmark Get at 1000 crumbs: measure Table.Get latency from 1000 seeded
    crumbs'
- id: F6
  step: 'Benchmark Get at 10000 crumbs: measure Table.Get latency from 10000 seeded
    crumbs'
- id: F7
  step: 'Benchmark Set create at 10 crumbs: measure Table.Set latency for creating
    new crumbs (empty ID) with 10 existing crumbs'
- id: F8
  step: 'Benchmark Set create at 1000 crumbs: measure Table.Set latency for creating
    new crumbs with 1000 existing crumbs'
- id: F9
  step: 'Benchmark Set update at 10 crumbs: measure Table.Set latency for updating
    existing crumbs with 10 seeded crumbs'
- id: F10
  step: 'Benchmark Set update at 1000 crumbs: measure Table.Set latency for updating
    existing crumbs with 1000 seeded crumbs'
- id: F11
  step: 'Benchmark Delete at 10 crumbs: measure Table.Delete latency including create-then-delete
    cycle with 10 seeded crumbs'
- id: F12
  step: 'Benchmark Delete at 1000 crumbs: measure Table.Delete latency with 1000 seeded
    crumbs'
- id: F13
  step: 'Benchmark Fetch all at 100 crumbs: measure Table.Fetch with empty filter
    returning all 100 crumbs'
- id: F14
  step: 'Benchmark Fetch all at 1000 crumbs: measure Table.Fetch with empty filter
    returning all 1000 crumbs'
- id: F15
  step: 'Benchmark Fetch state at 100 crumbs: measure Table.Fetch with state filter
    on 100 crumbs'
- id: F16
  step: 'Benchmark Fetch state at 1000 crumbs: measure Table.Fetch with state filter
    on 1000 crumbs'
- id: F17
  step: 'Run full benchmark suite: execute go test -bench=. -benchmem and capture
    output'
- id: F18
  step: 'Record baseline: save benchmark output for future comparison with benchstat'
touchpoints:
- T1: 'Table interface: Get, Set, Delete, Fetch (prd001-cupboard-core R3)'
- T2: 'SQLite backend: entity hydration, dehydration, JSONL persistence (prd002-sqlite-backend
    R14, R15)'
- T3: 'SQLite indexes: idx_crumbs_state for state filter benchmarks (prd002-sqlite-backend
    R3.3)'
- T4: 'Cupboard interface: Attach, Detach for benchmark setup/teardown (prd001-cupboard-core
    R2)'
success_criteria:
- id: S1
  criterion: Each benchmark function completes without error
- id: S2
  criterion: Benchmark output includes ns/op for each operation
- id: S3
  criterion: Benchmark output includes B/op (bytes per operation) for each operation
- id: S4
  criterion: Benchmark output includes allocs/op (allocations per operation) for each
    operation
- id: S5
  criterion: Get benchmarks run at 4 scales (10, 100, 1000, 10000)
- id: S6
  criterion: Set create benchmarks run at 2 scales (10, 1000)
- id: S7
  criterion: Set update benchmarks run at 2 scales (10, 1000)
- id: S8
  criterion: Delete benchmarks run at 2 scales (10, 1000)
- id: S9
  criterion: Fetch all benchmarks run at 2 scales (100, 1000)
- id: S10
  criterion: Fetch state benchmarks run at 2 scales (100, 1000)
out_of_scope:
- Property operations (SetProperty, GetProperty, ClearProperty) — see rel02.0
- Fetch with properties filter — requires rel02.0 property system
- Fetch with limit/pagination — not yet specified
- Concurrent benchmark scenarios
- Cross-table benchmarks (trails, metadata, links)
- Benchmark regression detection automation
test_suite: test-rel01.0
