id: rel01.0-uc001-cupboard-lifecycle
title: Configuration and Cupboard Lifecycle
summary: |
  An application initializes a Cupboard with a typed Config struct, attaches
  to a SQLite backend, accesses tables for data operations, and detaches to
  release resources. This tracer bullet validates the configuration workflow
  and cupboard lifecycle management defined in prd001-cupboard-core.
actor: Developer integrating the Crumbs library into their application
trigger: Application startup requiring backend connection and data operations
flow:
  - id: F1
    step: "Create configuration: construct a Config struct specifying Backend as sqlite and DataDir as the path to the data directory"
  - id: F2
    step: "Validate configuration: optionally validate the Config before calling Attach; invalid configurations fail at Attach time with a descriptive error"
  - id: F3
    step: "Create Cupboard instance: instantiate the Cupboard; at this point the cupboard is not attached to any backend"
  - id: F4
    step: "Attach to backend: call Attach(config) on the Cupboard; validates config, creates DataDir if needed, initializes SQLite schema, and seeds built-in data"
  - id: F5
    step: "Handle attach errors: if Attach fails log the error and exit or retry; if Attach is called on an already-attached cupboard it returns ErrAlreadyAttached"
  - id: F6
    step: "Access tables: call GetTable for crumbs, properties, and other standard tables; each returns a Table interface ready for Get, Set, Delete, and Fetch operations"
  - id: F7
    step: "Verify connection: perform a simple operation such as Fetch with an empty filter to confirm the backend is working"
  - id: F8
    step: "Perform data operations: use the tables for normal application work with CRUD operations; entity IDs are UUID v7 generated on Set when the ID field is empty"
  - id: F9
    step: "Detach from backend: when the application shuts down call Detach(); blocks until in-flight operations complete then closes database connections"
  - id: F10
    step: "Verify detach: after Detach any Cupboard operation returns ErrCupboardDetached; the application must create a new Cupboard instance to reconnect"
touchpoints:
  - T1: "Config struct: construction with Backend and DataDir fields (prd001-cupboard-core R1)"
  - T2: "Cupboard interface: Attach, Detach, GetTable (prd001-cupboard-core R2)"
  - T3: "Table interface: Fetch for connection verification (prd001-cupboard-core R2)"
  - T4: "Attach idempotency and validation (prd001-cupboard-core R4)"
  - T5: "Detach resource release and idempotency (prd001-cupboard-core R5)"
  - T6: "Error handling after detach (prd001-cupboard-core R6)"
  - T7: "Standard error types: ErrAlreadyAttached, ErrCupboardDetached, ErrTableNotFound (prd001-cupboard-core R7)"
success_criteria:
  - id: S1
    criterion: Config struct is created with Backend=sqlite and valid DataDir
  - id: S2
    criterion: Attach(config) returns nil and initializes the backend
  - id: S3
    criterion: Attach on an already-attached cupboard returns ErrAlreadyAttached
  - id: S4
    criterion: GetTable(crumbs) returns a valid Table interface
  - id: S5
    criterion: GetTable(unknown) returns ErrTableNotFound
  - id: S6
    criterion: Fetch on a table returns an empty slice or populated data if present
  - id: S7
    criterion: Detach() returns nil and releases all resources
  - id: S8
    criterion: Detach on an already-detached cupboard returns nil (idempotent)
  - id: S9
    criterion: GetTable after Detach returns ErrCupboardDetached
out_of_scope:
  - Connection pooling or retry policies
  - File-based configuration loading (JSON/YAML parsing)
test_suite: test-rel01.0
