id: rel01.1-uc005-flat-self-hosting
title: Flat Self-Hosting
summary: 'The cupboard CLI tracks development work on the crumbs repository using
  only

  core storage features. The do-work.sh and make-work.sh scripts run end-to-end

  using generic table commands (get, set, list, delete) and crumb commands.

  This validates that cupboard works as an issue tracker for real agent workflows

  without requiring properties, trails, or epics.

  '
actor: Coding agent (e.g., Claude Code) working on the crumbs codebase via do-work.sh
  and make-work.sh scripts
trigger: Cupboard CLI providing the table and crumb commands that scripts need
flow:
- id: F1
  step: 'Initialize cupboard: run cupboard init to create data directory and empty
    JSONL files'
- id: F2
  step: 'Create crumbs via generic table command: run cupboard set crumbs '''' ''{"Name":"...","State":"draft"}'''
- id: F3
  step: 'List crumbs via generic table command: run cupboard list crumbs to see all
    crumbs as JSON'
- id: F4
  step: 'Update crumb state via generic table command: run cupboard set crumbs <id>
    ''{...}'' to change state'
- id: F5
  step: 'Get crumb details via generic table command: run cupboard get crumbs <id>
    to view a single crumb'
- id: F6
  step: 'Delete crumbs via generic table command: run cupboard delete crumbs <id>
    to remove a crumb'
- id: F7
  step: 'Integrate do-work.sh script: use cupboard commands to pick a task, claim
    it, and close it after completion'
- id: F8
  step: 'Integrate make-work.sh script: use cupboard commands to list existing issues
    and create new ones'
- id: F9
  step: 'Commit JSONL files to git: per eng01-git-integration, JSONL files are committed
    as part of session completion'
touchpoints:
- T1: 'cupboard CLI (cmd/cupboard): generic table commands get, set, list, delete
    (prd009-cupboard-cli R3)'
- T2: 'Cupboard library (pkg/types): Cupboard interface with GetTable, Table interface
    for CRUD (prd001-cupboard-core R2, R3)'
- T3: 'SQLite backend (internal/sqlite): storage, JSONL persistence, query engine
    (prd002-sqlite-backend R1-R5)'
- T4: 'Crumb entity (pkg/types): Name, State, CreatedAt, UpdatedAt fields (prd003-crumbs-interface
    R1)'
- T5: 'do-work.sh: task picking (list with filter), worktree management, agent invocation'
- T6: 'make-work.sh: work creation (set with empty ID), issue listing'
- T7: '.claude/rules/: agent workflow instructions (eng01-git-integration)'
success_criteria:
- id: S1
  criterion: cupboard init creates data directory and JSONL files
- id: S2
  criterion: cupboard set crumbs '' '{"Name":"Test","State":"draft"}' creates a crumb
    and returns JSON with CrumbID
- id: S3
  criterion: cupboard list crumbs returns all crumbs as JSON array
- id: S4
  criterion: cupboard list crumbs State=draft returns only draft crumbs
- id: S5
  criterion: cupboard set crumbs <id> '{...}' updates crumb state to taken
- id: S6
  criterion: cupboard set crumbs <id> '{...}' updates crumb state to pebble (close)
- id: S7
  criterion: cupboard get crumbs <id> returns crumb details as JSON
- id: S8
  criterion: do-work.sh runs a full cycle (pick, claim, work, close) using cupboard
    commands
- id: S9
  criterion: make-work.sh creates issues via cupboard and commits JSONL changes
- id: S10
  criterion: JSONL files persist data and survive database deletion
out_of_scope:
- Properties (type, priority, labels, description) - see rel02.0
- Issue-tracking CLI commands (ready, create, update, close) - see rel02.1-uc003
- Trails and trail-scoped crumbs - see rel03.0
- Epic and task hierarchy (child_of links) - see rel02.1-uc003
- Comments and metadata - see rel02.1-uc004
- Multi-agent coordination
test_suite: test-rel01.1
