id: rel01.0-uc002-table-crud
title: Table Interface CRUD Operations
summary: |
  A developer attaches a SQLite backend, obtains a Table reference, and
  exercises the four uniform Table operations (Get, Set, Delete, Fetch) to
  create, retrieve, update, and remove entities. This tracer bullet validates
  the ORM-style pattern where callers create entity structs, persist them
  through Table.Set, retrieve them with Table.Get, query with Table.Fetch, and
  remove with Table.Delete. The focus is on the Table interface contract, not
  on any entity-specific behavior.
actor: Developer or agent working through the Cupboard API
trigger: Need to verify that the Table interface provides correct CRUD behavior across all standard tables with JSONL persistence and UUID v7 generation
flow:
  - id: F1
    step: "Attach backend: construct a Cupboard, call Attach(config) with a SQLite backend configuration; the backend creates DataDir, initializes JSONL files, creates cupboard.db, and seeds built-in data"
  - id: F2
    step: "Get a table: call cupboard.GetTable(crumbs) to obtain a Table; the returned Table provides Get, Set, Delete, and Fetch operations"
  - id: F3
    step: "Create an entity (Set with empty ID): construct a Crumb struct and call table.Set with empty ID; the backend generates a UUID v7, initializes timestamps, inserts into SQLite, and persists to JSONL"
  - id: F4
    step: "Retrieve the entity (Get): call table.Get(id) with the generated ID; the backend queries SQLite, hydrates the row into the entity struct, and returns it"
  - id: F5
    step: "Verify round-trip fidelity: compare the retrieved entity fields against what was created; CrumbID, Name, State, CreatedAt, and UpdatedAt must match"
  - id: F6
    step: "Update the entity (Set with existing ID): modify a field on the struct and call table.Set(id, crumb); the backend updates the SQLite row and writes the change to JSONL"
  - id: F7
    step: "Verify the update persists: call table.Get(id) again; the modified field must reflect the change; UpdatedAt must be equal to or later than the previous value"
  - id: F8
    step: "Create a second entity: call table.Set with empty ID to create another entity; the generated ID must differ from the first"
  - id: F9
    step: "Fetch all entities: call table.Fetch with an empty filter; the result must contain both entities"
  - id: F10
    step: "Fetch with filter: call table.Fetch with a state filter; the result must include only entities matching the filter"
  - id: F11
    step: "Delete an entity: call table.Delete(id); the backend removes the entity from SQLite and JSONL; a subsequent Get returns an error"
  - id: F12
    step: "Get nonexistent entity: call table.Get with a nonexistent ID; the operation must return an error indicating the entity was not found"
  - id: F13
    step: "Delete nonexistent entity: call table.Delete with a nonexistent ID; the operation must return an error"
  - id: F14
    step: "Verify JSONL persistence: inspect the JSONL file to confirm that create, update, and delete operations are reflected; each line is valid JSON"
  - id: F15
    step: "Repeat on every standard table: for each of trails, properties, metadata, links, and stashes, call cupboard.GetTable(name), create an entity with Set (empty ID), retrieve it with Get, list with Fetch, and delete with Delete; the same Table interface contract holds across all six standard tables"
  - id: F16
    step: "Detach: call cupboard.Detach() to release resources; subsequent Table operations return ErrCupboardDetached"
touchpoints:
  - T1: "Cupboard interface: Attach, GetTable, Detach (prd001-cupboard-core R2)"
  - T2: "Table interface: Get, Set, Delete, Fetch (prd001-cupboard-core R2)"
  - T3: "SQLite backend: UUID v7 generation, hydration, dehydration, JSONL persistence (prd002-sqlite-backend R5, R14)"
  - T4: "Table.Set with empty ID generates UUID v7 and creates entity (prd002-sqlite-backend R5)"
  - T5: "Table.Get retrieves and hydrates entity from SQLite (prd002-sqlite-backend R14)"
  - T6: "Table.Fetch returns matching entities; empty filter returns all (prd001-cupboard-core R2)"
  - T7: "Table.Delete removes entity from SQLite and JSONL (prd002-sqlite-backend R5)"
  - T8: "JSONL files are human-readable and reflect all write operations (prd002-sqlite-backend R5, R16)"
success_criteria:
  - id: S1
    criterion: Set with empty ID returns a UUID v7 and persists to JSONL
  - id: S2
    criterion: Get(id) returns the entity with all fields matching what was created
  - id: S3
    criterion: Set(id, entity) updates the entity; Get confirms the change
  - id: S4
    criterion: Fetch with empty filter returns all entities in the table
  - id: S5
    criterion: Fetch with filter returns only matching entities
  - id: S6
    criterion: Delete(id) removes the entity; subsequent Get returns an error
  - id: S7
    criterion: Get and Delete on nonexistent IDs return errors
  - id: S8
    criterion: The same operations (Set, Get, Fetch, Delete) work on all six standard tables (crumbs, trails, properties, metadata, links, stashes)
  - id: S9
    criterion: JSONL file reflects all create, update, and delete operations
  - id: S10
    criterion: Detach prevents further operations with ErrCupboardDetached
out_of_scope:
  - Crumb state machine transitions (SetState, Pebble, Dust) — see rel01.0-uc003
  - Entity method behavior beyond field assignment — see rel01.0-uc003
  - Property operations (SetProperty, GetProperty, ClearProperty) — see rel02.0-uc001
  - Trail lifecycle (Complete, Abandon, cascade behavior) — see rel03.0-uc001
  - Concurrent access patterns
  - Error recovery (corrupt JSONL, I/O failures)
test_suite: test-rel01.0
