id: rel01.0-uc003-crumb-lifecycle
title: Crumb Entity Operations
summary: |
  A developer creates crumbs and exercises the full crumb state machine,
  transitioning crumbs through draft to pending to ready to taken to pebble
  (success) and draft to dust (failure). This tracer bullet validates the
  Crumb entity methods (SetState, Pebble, Dust), timestamp behavior on state
  transitions, and state-based filtering. The focus is on crumbs-specific
  behavior, not on the generic Table interface (see rel01.0-uc002).
actor: Developer or agent managing work items
trigger: Need to verify that crumbs follow the documented state machine and that entity methods correctly modify state, update timestamps, and interact with Table persistence
flow:
  - id: F1
    step: "Setup: attach a Cupboard with SQLite backend and obtain the crumbs table via cupboard.GetTable(crumbs)"
  - id: F2
    step: "Create crumb in draft state: call table.Set with empty ID and a new Crumb; the backend generates a UUID v7 and initializes the crumb with State draft, CreatedAt, UpdatedAt, and an empty Properties map"
  - id: F3
    step: "Verify initial state: retrieve the crumb via table.Get(id); confirm State is draft, timestamps are set, and Properties is initialized"
  - id: F4
    step: "Transition draft to pending: call crumb.SetState(pending) then table.Set(id, crumb); retrieve and confirm State is pending and UpdatedAt has advanced"
  - id: F5
    step: "Transition pending to ready: call crumb.SetState(ready) then table.Set(id, crumb); retrieve and confirm State is ready"
  - id: F6
    step: "Transition ready to taken: call crumb.SetState(taken) then table.Set(id, crumb); retrieve and confirm State is taken"
  - id: F7
    step: "Complete via Pebble: call crumb.Pebble() then table.Set(id, crumb); retrieve and confirm State is pebble (terminal success); UpdatedAt must reflect the transition time"
  - id: F8
    step: "Create a second crumb for the failure path: call table.Set with empty ID and a new Crumb; verify State is draft"
  - id: F9
    step: "Fail via Dust: call crumb2.Dust() then table.Set(id2, crumb2); retrieve and confirm State is dust (terminal failure)"
  - id: F10
    step: "Filter by state: call table.Fetch with states filter for draft; verify the result excludes both the pebble crumb and the dust crumb"
  - id: F11
    step: "Filter for terminal states: call table.Fetch with states filter for pebble; verify only the completed crumb is returned; repeat for dust"
  - id: F12
    step: "Create crumb and transition to dust from any non-terminal state: create a third crumb, transition to ready, then call Dust(); verify the crumb reaches dust regardless of its previous state"
  - id: F13
    step: "Verify UpdatedAt tracks transitions: for each state transition confirm that UpdatedAt changed and is equal to or later than the previous value; CreatedAt must remain unchanged"
  - id: F14
    step: "Detach: call cupboard.Detach()"
touchpoints:
  - T1: "Table interface: Get, Set, Fetch for persistence and retrieval (prd001-cupboard-core R2)"
  - T2: "Crumb entity: SetState, Pebble, Dust methods (prd003-crumbs-interface R2)"
  - T3: "Crumb state machine: draft to pending to ready to taken to pebble; any to dust (prd003-crumbs-interface R2, R4, R5)"
  - T4: "Crumb creation defaults to draft state with initialized timestamps (prd003-crumbs-interface R1, R3)"
  - T5: "UpdatedAt advances on every state transition; CreatedAt remains constant (prd003-crumbs-interface R3)"
  - T6: "State-based Fetch filtering correctly includes and excludes crumbs by state (prd003-crumbs-interface R9, R10)"
success_criteria:
  - id: S1
    criterion: New crumb starts in draft state with CreatedAt and UpdatedAt set
  - id: S2
    criterion: SetState(pending) transitions draft to pending
  - id: S3
    criterion: SetState(ready) transitions pending to ready
  - id: S4
    criterion: SetState(taken) transitions ready to taken
  - id: S5
    criterion: Pebble() transitions taken to pebble (terminal)
  - id: S6
    criterion: Dust() transitions draft to dust (terminal)
  - id: S7
    criterion: Dust() works from any non-terminal state (tested from ready)
  - id: S8
    criterion: UpdatedAt advances on each transition; CreatedAt stays constant
  - id: S9
    criterion: Fetch by state returns only crumbs in the requested state
  - id: S10
    criterion: Fetch excludes pebble and dust crumbs when filtering for non-terminal states
  - id: S11
    criterion: Properties map is initialized on creation
out_of_scope:
  - Generic Table CRUD operations (create, update, delete, fetch) — see rel01.0-uc002
  - Property operations (SetProperty, GetProperty, ClearProperty) — see rel02.0-uc001
  - Trail membership (belongs_to links) — see rel03.0-uc001
  - Crumb deletion (Table.Delete) — see rel01.0-uc002
  - Invalid state transition rejection (not enforced by the Table; agents define rules)
  - Concurrent state transitions
test_suite: test-rel01.0
