id: rel02.1-uc004-metadata-lifecycle
title: Metadata Lifecycle Operations
summary: 'A developer attaches metadata to crumbs using the comments and attachments

  schemas, retrieves metadata by ID, queries metadata using filters, and

  verifies that metadata entries are removed when the parent crumb is deleted.

  This tracer bullet validates the append-only metadata pattern where multiple

  entries accumulate on a single crumb, and the cascade delete behavior that

  maintains referential integrity.

  '
actor: Developer or agent working through the Cupboard API
trigger: Need to attach supplementary information to crumbs (comments, attachments)
  and verify metadata lifecycle behavior
flow:
- id: F1
  step: 'Attach backend: construct a Cupboard, call Attach(config) with a SQLite backend
    configuration; the backend creates DataDir and initializes the metadata table
    with built-in schemas'
- id: F2
  step: 'Create a crumb: call table.Set on the crumbs table with an empty ID to create
    a crumb that will hold metadata'
- id: F3
  step: 'Add a comment: construct a Metadata struct with TableName=comments and Content=text,
    call table.Set on the metadata table with empty ID; the backend generates a UUID
    v7 and persists the entry'
- id: F4
  step: 'Add a second comment: call table.Set again with different content; verify
    that multiple metadata entries accumulate for the same crumb'
- id: F5
  step: 'Add an attachment: construct a Metadata struct with TableName=attachments
    and Content=JSON object, call table.Set; the backend stores the JSON content as-is'
- id: F6
  step: 'Retrieve metadata by ID: call table.Get with the metadata ID; the backend
    returns the Metadata struct with all fields populated'
- id: F7
  step: 'Filter by schema: call table.Fetch with filter schema=comments; the result
    includes only comment entries'
- id: F8
  step: 'Filter by crumb_id: call table.Fetch with filter crumb_id=crumb-uuid; the
    result includes only entries for that crumb'
- id: F9
  step: 'Combine filters: call table.Fetch with both schema and crumb_id filters;
    verify that filters are ANDed'
- id: F10
  step: 'Verify ErrNotFound: call table.Get with a nonexistent metadata ID; the operation
    returns ErrNotFound'
- id: F11
  step: 'Verify ErrInvalidID: call table.Get with an empty ID; the operation returns
    ErrInvalidID'
- id: F12
  step: 'Delete the parent crumb: call table.Delete on the crumbs table for the crumb
    with metadata'
- id: F13
  step: 'Verify cascade delete: call table.Fetch with crumb_id filter for the deleted
    crumb; the result is empty, confirming all metadata was removed'
- id: F14
  step: 'Detach: call cupboard.Detach() to release resources'
touchpoints:
- T1: 'Cupboard interface: Attach, GetTable, Detach (prd001-cupboard-core R2)'
- T2: 'Table interface: Get, Set, Delete, Fetch (prd001-cupboard-core R3)'
- T3: 'Metadata struct: MetadataID, CrumbID, TableName, Content, PropertyID, CreatedAt
    (prd005-metadata-interface R1)'
- T4: 'Built-in schemas: comments (text), attachments (json) (prd005-metadata-interface
    R3)'
- T5: 'Metadata creation via Table.Set: UUID v7 generation, timestamp (prd005-metadata-interface
    R4)'
- T6: 'Metadata retrieval via Table.Get: type assertion to *Metadata (prd005-metadata-interface
    R5)'
- T7: 'Filter map: schema, crumb_id filters (prd005-metadata-interface R7)'
- T8: 'Cascade delete: metadata removed when crumb deleted (prd005-metadata-interface
    R6.5)'
- T9: 'Error types: ErrNotFound, ErrInvalidID (prd005-metadata-interface R10)'
success_criteria:
- id: S1
  criterion: Table.Set with empty ID generates a UUID v7 for metadata and persists
    to storage
- id: S2
  criterion: Multiple metadata entries can be added to the same crumb (additive, not
    replacement)
- id: S3
  criterion: Comments schema stores plain text content
- id: S4
  criterion: Attachments schema stores JSON content as-is
- id: S5
  criterion: Table.Get retrieves metadata with all fields matching what was created
- id: S6
  criterion: Table.Fetch with schema filter returns only matching entries
- id: S7
  criterion: Table.Fetch with crumb_id filter returns only entries for that crumb
- id: S8
  criterion: Table.Fetch with multiple filters ANDs them together
- id: S9
  criterion: Table.Get with nonexistent ID returns ErrNotFound
- id: S10
  criterion: Table.Get with empty ID returns ErrInvalidID
- id: S11
  criterion: When a crumb is deleted, all its metadata entries are also deleted
- id: S12
  criterion: Table.Fetch for deleted crumb returns empty result
out_of_scope:
- Schema registration for custom metadata types (see prd005-metadata-interface R9)
- PropertyID linking for property-specific metadata
- Content validation (content_contains filter, JSON validation)
- Limit and offset pagination
- Metadata deletion via Table.Delete (append-only convention)
- JSONL persistence verification (covered by rel01.0-uc002)
test_suite: test-rel02.1
