id: rel03.0-uc003-stash-operations
title: Stash Operations
summary: |
  A developer creates stashes of each type (resource, artifact, context, counter,
  lock) to share state between crumbs. This tracer bullet validates stash creation,
  value operations (SetValue/GetValue), counter operations (Increment), lock
  operations (Acquire/Release with reentrant and contention semantics), version
  tracking across mutations, and fetch with filters through the Table interface.
actor: Coding agent or developer managing shared state between crumbs
trigger: Need to create, access, or coordinate shared state in a trail
flow:
  - id: F1
    step: "Create cupboard and get stashes table: construct a Cupboard via sqlite.NewBackend(), call Attach(config), and get stashes table"
  - id: F2
    step: "Create resource stash: create a stash with type 'resource' containing URI and kind"
  - id: F3
    step: "Verify resource stash creation: confirm StashID generated, Version is 1, CreatedAt set"
  - id: F4
    step: "Create artifact stash: create a stash with type 'artifact' containing path and producer"
  - id: F5
    step: "Create context stash: create a stash with type 'context' containing configuration data"
  - id: F6
    step: "Test SetValue on context stash: update value and verify Version increments"
  - id: F7
    step: "Test GetValue retrieves current value: confirm value matches what was set"
  - id: F8
    step: "Create counter stash: create a stash with type 'counter' with initial value 0"
  - id: F9
    step: "Test Increment with positive delta: call Increment(5), verify returns 5 and Version increments"
  - id: F10
    step: "Test Increment with negative delta: call Increment(-2), verify returns 3 and Version increments"
  - id: F11
    step: "Test multiple increments: verify accumulated value is correct across operations"
  - id: F12
    step: "Create lock stash: create a stash with type 'lock' with nil initial value"
  - id: F13
    step: "Test Acquire lock: call Acquire('worker-1'), verify success and Version increments"
  - id: F14
    step: "Test reentrant acquire: call Acquire('worker-1') again, verify success without error"
  - id: F15
    step: "Test contention (ErrLockHeld): call Acquire('worker-2'), verify ErrLockHeld returned"
  - id: F16
    step: "Test Release lock: call Release('worker-1'), verify success and Version increments"
  - id: F17
    step: "Test wrong holder release (ErrNotLockHolder): call Release('worker-2') on unlocked lock"
  - id: F18
    step: "Fetch stashes by stash_type filter: query stashes table with stash_type filter"
  - id: F19
    step: "Fetch stashes by name filter: query stashes table with name filter"
  - id: F20
    step: "Delete stash: remove a stash and verify ErrNotFound on subsequent Get"
  - id: F21
    step: "Query stash history after multiple mutations: call FetchStashHistory and verify all operations recorded"
  - id: F22
    step: "Verify history entries: confirm entries have correct version, operation, and value snapshots"
  - id: F23
    step: "Detach the cupboard: call cupboard.Detach()"
touchpoints:
  - T1: "Cupboard interface: Attach, Detach, GetTable (prd001-cupboard-core R2)"
  - T2: "Table (stashes): Get, Set, Delete, Fetch (prd001-cupboard-core R3)"
  - T3: "Stash entity: StashID, Name, StashType, Value, Version, CreatedAt fields (prd008-stash-interface R1)"
  - T4: "Stash types: resource, artifact, context, counter, lock (prd008-stash-interface R2)"
  - T5: "SetValue/GetValue methods for value access (prd008-stash-interface R4)"
  - T6: "Increment method for counter operations (prd008-stash-interface R5)"
  - T7: "Acquire/Release methods for lock operations (prd008-stash-interface R6)"
  - T8: "Version tracking across mutations (prd008-stash-interface R1.6)"
  - T9: "Filter map for stash queries: stash_type, name (prd008-stash-interface R9)"
  - T10: "Stash history tracking: FetchStashHistory method (prd008-stash-interface R7)"
success_criteria:
  - id: S1
    criterion: Stash created via Table.Set generates UUID v7 for StashID
  - id: S2
    criterion: All five stash types can be created (resource, artifact, context, counter, lock)
  - id: S3
    criterion: SetValue updates value and increments Version; returns ErrInvalidStashType for lock type
  - id: S4
    criterion: GetValue returns current value or nil if not set
  - id: S5
    criterion: Increment adds delta to counter value and increments Version; returns ErrInvalidStashType for non-counter
  - id: S6
    criterion: Increment with negative delta decrements the counter correctly
  - id: S7
    criterion: Acquire sets holder and increments Version; returns ErrLockHeld if held by different holder
  - id: S8
    criterion: Acquire by same holder succeeds (reentrant) without error
  - id: S9
    criterion: Release clears lock and increments Version; returns ErrNotLockHolder if wrong holder
  - id: S10
    criterion: Version starts at 1 and increments on every mutation
  - id: S11
    criterion: Fetch with stash_type filter returns only stashes of that type
  - id: S12
    criterion: Fetch with name filter returns stash matching that name
  - id: S13
    criterion: Delete removes stash; subsequent Get returns ErrNotFound
  - id: S14
    criterion: History entry created for each stash mutation (create, set, increment, acquire, release)
  - id: S15
    criterion: History entries queryable by stash ID via FetchStashHistory, ordered by version ascending
out_of_scope:
  - Stash scoping via scoped_to links (see rel03.0-uc002)
  - Blocking lock acquisition with timeout
  - Stash name uniqueness validation (backend may enforce)
  - Concurrent stash operations
test_suite: test-rel03.0
