id: rel01.1-uc002-jsonl-git-roundtrip
title: JSONL Git Roundtrip
summary: 'A user creates crumbs, commits the JSONL files to git, deletes the SQLite

  database, re-attaches the cupboard, and verifies that all data is intact.

  This validates that JSONL files are the source of truth and that the SQLite

  backend rebuilds state correctly from JSONL on attach.

  '
actor: Developer or coding agent working in a git repository with cupboard data
trigger: Any scenario where the SQLite database is missing or stale, such as cloning
  a repository, switching branches, or recovering from a corrupted database
flow:
- id: F1
  step: 'Initialize cupboard in git repository: create data directory, config, and
    .gitignore'
- id: F2
  step: Create crumbs using the cupboard CLI
- id: F3
  step: Verify JSONL files exist and contain the data
- id: F4
  step: Commit the JSONL files to git
- id: F5
  step: Verify SQLite database exists (pre-deletion baseline)
- id: F6
  step: Delete SQLite database to simulate fresh clone or branch switch
- id: F7
  step: Re-attach by running a cupboard command
- id: F8
  step: Verify all crumbs are intact
- id: F9
  step: Verify queries work correctly
- id: F10
  step: Modify data and verify JSONL is updated
- id: F11
  step: Commit the updated JSONL files
- id: F12
  step: 'Repeat the roundtrip: delete database, re-attach, verify'
- id: F13
  step: 'Test on_close sync strategy: verify JSONL deferred until Detach'
- id: F14
  step: 'Test batch sync strategy: verify flush at BatchSize threshold'
- id: F15
  step: 'Test immediate sync strategy (default): verify every write persists'
touchpoints:
- T1: 'SQLite backend startup sequence: delete db, create schema, load JSONL (prd002-sqlite-backend
    R4)'
- T2: 'SQLite backend JSONL as source of truth: cupboard.db is ephemeral (prd002-sqlite-backend
    R1.2)'
- T3: SQLite backend atomic write pattern for JSONL (prd002-sqlite-backend R5.2)
- T4: SQLite backend immediate sync strategy (prd002-sqlite-backend R16.2)
- T5: SQLite backend entity hydration from SQLite rows (prd002-sqlite-backend R14)
- T6: 'Cupboard interface: Attach initializes backend (prd001-cupboard-core R4)'
- T7: 'Git integration: JSONL files committed, cupboard.db gitignored (eng01-git-integration)'
- T8: 'Git integration: Commit JSONL alongside code changes (eng01-git-integration)'
- T9: 'SQLite backend on_close sync strategy: defer writes until Detach (prd002-sqlite-backend
    R16.3)'
- T10: 'SQLite backend batch sync strategy: flush at BatchSize or BatchInterval (prd002-sqlite-backend
    R16.4-R16.6)'
- T11: 'SQLite backend sync strategy dispatch: backend reads SyncStrategy from config
    (prd002-sqlite-backend R16.1)'
success_criteria:
- id: S1
  criterion: git init and .gitignore setup completes with cupboard.db gitignored
- id: S2
  criterion: cupboard create produces crumbs with JSON output including crumb_id
- id: S3
  criterion: cat data/crumbs.jsonl shows one crumb per line
- id: S4
  criterion: ls data/cupboard.db confirms SQLite database exists
- id: S5
  criterion: git add data/*.jsonl and git commit succeeds with JSONL files tracked
- id: S6
  criterion: rm data/cupboard.db successfully deletes database
- id: S7
  criterion: cupboard list after database deletion returns correct count (data intact)
- id: S8
  criterion: cupboard show after rebuild displays correct title, state, and type
- id: S9
  criterion: ls data/cupboard.db confirms database regenerated on attach
- id: S10
  criterion: cupboard update persists state changes to JSONL
- id: S11
  criterion: State changes survive additional database deletion and rebuild cycles
- id: S12
  criterion: on_close strategy defers all JSONL writes until Detach
- id: S13
  criterion: batch strategy flushes at BatchSize threshold
- id: S14
  criterion: immediate strategy (default) persists every write immediately
out_of_scope:
- Merge conflict resolution when JSONL files diverge between branches (eng01-git-integration
  describes this but not validated here)
- Trail-scoped worktrees (eng01-git-integration Trails as Worktrees)
- Corrupt JSONL recovery (prd002-sqlite-backend R7 describes error handling but this
  use case assumes valid files)
- Cross-process access (prd002-sqlite-backend R8.5 explicitly does not support this)
- Batch interval timer edge cases (rapid attach/detach cycles, timer races)
test_suite: test-rel01.1
