id: rel03.1-uc001-self-hosting-with-epics
title: Self-Hosting with Epics via Trails
summary: 'The cupboard CLI tracks development work on the crumbs repository using
  trails

  as epic equivalents. An agent creates a trail to group related tasks (crumbs),

  associates crumbs with the trail via belongs_to links, and uses trail lifecycle

  operations to control grouped work. Completing a trail finalizes all its tasks;

  abandoning a trail discards them. This validates full-featured self-hosting that

  replaces beads epics with cupboard trails.

  '
actor: Coding agent (e.g., Claude Code) working on the crumbs codebase via do-work.sh
  and make-work.sh scripts
trigger: Need to organize related tasks under an epic-like container with lifecycle
  control
flow:
- id: F1
  step: 'Create an epic trail: run cupboard set trails '''' ''{"State":"draft"}''
    to create a trail that will group related tasks'
- id: F2
  step: 'Transition trail to active: run cupboard set trails <trail_id> ''{"State":"active"}'''
- id: F3
  step: 'Create tasks for the epic: run cupboard set crumbs '''' ''{"Name":"Task 1","State":"draft"}''
    for each task'
- id: F4
  step: 'Associate crumbs with trail: run cupboard set links '''' ''{"LinkType":"belongs_to","FromID":"<crumb_id>","ToID":"<trail_id>"}'''
- id: F5
  step: 'Query crumbs by epic: run cupboard list links LinkType=belongs_to ToID=<trail_id>'
- id: F6
  step: 'Work on tasks: pick a task, claim it (set State to taken), complete work,
    close it (set State to pebble)'
- id: F7
  step: 'Add more tasks to epic during work: create new crumbs and link them to the
    trail'
- id: F8
  step: 'Complete the epic trail: run cupboard set trails <trail_id> ''{"State":"completed"}'''
- id: F9
  step: 'Verify crumbs are permanent: run cupboard list links LinkType=belongs_to
    ToID=<trail_id> returns empty'
- id: F10
  step: 'Create another epic for abandonment scenario: create trail, add crumbs, link
    them'
- id: F11
  step: 'Abandon the failed epic: run cupboard set trails <trail_id> ''{"State":"abandoned"}'''
- id: F12
  step: 'Verify cascade deletion: cupboard get crumbs <crumb_id> returns error for
    abandoned crumbs'
- id: F13
  step: 'Integrate with do-work.sh: script creates trail for related work, adds crumbs,
    completes trail on merge'
- id: F14
  step: 'Integrate with make-work.sh: script creates trails as epics and groups child
    tasks'
- id: F15
  step: 'Commit JSONL files to git: per eng01-git-integration, all JSONL files are
    committed including trails and links'
touchpoints:
- T1: 'cupboard CLI (cmd/cupboard): generic table commands get, set, list, delete
    for trails, crumbs, and links'
- T2: 'Cupboard library (pkg/types): Cupboard interface with GetTable, Table interface
    for CRUD (prd001-cupboard-core R2, R3)'
- T3: 'Trail entity (pkg/types): State field, lifecycle transitions draft→active→completed/abandoned
    (prd006-trails-interface R2)'
- T4: 'Trail completion semantics: removes belongs_to links, crumbs become permanent
    (prd006-trails-interface R5)'
- T5: 'Trail abandonment semantics: deletes associated crumbs atomically (prd006-trails-interface
    R6)'
- T6: 'Links table: belongs_to links associate crumbs with trails (prd007-links-interface
    R2.1)'
- T7: 'SQLite backend (internal/sqlite): storage, JSONL persistence, cascade operations
    (prd002-sqlite-backend R1-R5)'
- T8: 'do-work.sh: optionally creates trail for grouped work, completes trail on merge'
- T9: 'make-work.sh: maps epics to trails, child tasks to belongs_to-linked crumbs'
- T10: '.claude/rules/: agent workflow instructions referencing trail-based epic management'
success_criteria:
- id: S1
  criterion: cupboard set trails '' '{"State":"draft"}' creates a trail and returns
    JSON with TrailID
- id: S2
  criterion: cupboard set links '' '{"LinkType":"belongs_to",...}' creates belongs_to
    link between crumb and trail
- id: S3
  criterion: cupboard list links LinkType=belongs_to ToID=<trail_id> returns all crumbs
    in the epic
- id: S4
  criterion: Crumbs in active trail are queryable and modifiable
- id: S5
  criterion: cupboard set trails <id> '{"State":"completed"}' removes belongs_to links
- id: S6
  criterion: After trail completion, crumbs persist without belongs_to links (permanent)
- id: S7
  criterion: cupboard set trails <id> '{"State":"abandoned"}' deletes associated crumbs
    atomically
- id: S8
  criterion: After trail abandonment, cupboard get crumbs <crumb_id> returns not found
    for deleted crumbs
- id: S9
  criterion: Trail remains in database after abandonment (for audit)
- id: S10
  criterion: do-work.sh can run a full cycle with trail-based epic grouping
- id: S11
  criterion: make-work.sh can create epics as trails and group child tasks
- id: S12
  criterion: JSONL files (trails.jsonl, links.jsonl) persist and are committed to
    git
out_of_scope:
- Nested trails (trails containing trails) - not supported per rel03.0-uc001
- Trail merging or splitting
- Concurrent trail operations
- Multi-agent coordination (single agent self-hosting)
- Remote backends (SQLite only)
- Properties for trails (trail properties are future work per ARCHITECTURE)
test_suite: test-rel03.1
