id: rel99.0-uc001-blazes-templates
title: Agent Uses Blazes (Workflow Templates)
summary: 'A coding agent discovers predefined workflow templates (blazes) from a template

  directory, reads template metadata to understand available workflows, and selects

  a template based on semantic match to the current task. This tracer bullet validates

  the template discovery and selection flow that enables agents to reuse common

  workflow patterns.

  '
actor: Coding agent (e.g., Claude Code) that needs to perform a recognized workflow
  pattern such as bug fixing, feature implementation, or code review
trigger: Agent encountering a task that matches a known workflow category; instead
  of constructing a workflow from scratch, the agent discovers and selects a predefined
  template
flow:
- id: F1
  step: 'Discover template directory: locate the template directory configured via
    Cupboard or a well-known path such as .crumbs/blazes/'
- id: F2
  step: 'List available templates: read the directory and enumerate all .yaml or .yml
    files, each representing one blaze'
- id: F3
  step: 'Read template metadata: parse each template YAML and extract name, description,
    tags, and parameters without parsing the full trail definition'
- id: F4
  step: 'Match task to template: compare current task context against template metadata
    using tags for semantic matching (e.g., task fix the login bug matches templates
    tagged with bug-fix, debugging)'
- id: F5
  step: 'Select template: choose the best-matching template; if multiple match, prompt
    user or select based on priority or specificity'
- id: F6
  step: 'Extract parameters: read the parameters section with name, description, type,
    and optional default; determine which can be inferred from context and which require
    user input'
- id: F7
  step: 'Present selection: display selected template name, description, and required
    parameters to the user for confirmation'
touchpoints:
- T1: 'prd011-blazes-templates R4: template directory discovery at well-known or configured
    path'
- T2: 'prd011-blazes-templates R5: template file enumeration from directory'
- T3: 'prd011-blazes-templates R1: Blaze template YAML schema with name, description,
    tags, parameters'
- T4: 'prd011-blazes-templates R8: parameter extraction with context inference'
- T5: 'prd011-blazes-templates R6: tag-based matching of task context against template
    tags'
- T6: 'prd011-blazes-templates R7: template selection from matched candidates'
- T7: 'prd003-crumbs-interface R1: Crumb struct fields referenced in template trail
    definition'
- T8: 'prd006-trails-interface R3: trail creation referenced for future instantiation'
success_criteria:
- id: S1
  criterion: Agent discovers template directory at configured or well-known path
- id: S2
  criterion: Agent lists all .yaml/.yml files in the directory
- id: S3
  criterion: Agent parses template metadata (name, description, tags, parameters)
    without error
- id: S4
  criterion: Agent matches a task description to template tags
- id: S5
  criterion: Agent selects the best-matching template
- id: S6
  criterion: Agent extracts parameter definitions (name, type, description, default)
- id: S7
  criterion: Agent presents selected template and parameters to user
out_of_scope:
- Trail instantiation from template (requires prd-blazes-instantiation)
- Parameter value binding and placeholder expansion (requires prd-blazes-instantiation)
- Creating crumbs via Table.Set per prd003-crumbs-interface R3 (requires prd-blazes-instantiation)
- Creating trails via Table.Set per prd006-trails-interface R3 (requires prd-blazes-instantiation)
- Creating belongs_to links per prd006-trails-interface R7 (requires prd-blazes-instantiation)
- Template validation and error handling for malformed YAML (requires prd-blazes-schema)
- Template versioning or inheritance
- Remote template repositories
- Template creation or editing workflows
test_suite: test-rel99.0
